### ISSUE TITLE
Vuepress fails to run after setting theme

### ISSUE THREAD

**Issue by cfjedimaster** [ulivz/vuepress-theme-blog#4]
I installed @vuepress/blog as the readme explains, and set the theme in config.js, 

```js
module.exports = {
  title: 'Hello VuePress!',
  description: 'Just playing around',
  theme:'@vuepress/blog',
  themeConfig:{
  }
}
```

then ran `vuepress dev`. I got:

```
 /m/c/p/v/d/test3 vuepress dev                                                                                  09:55:11
Extracting site metadata...Error: [vuepress] Failed to load custom theme "@vuepress/blog". File vuepress-theme-@vuepress/blog/Layout.vue does not exist.
    at resolveOptions (/home/ray/.npm-global/lib/node_modules/vuepress/lib/prepare.js:132:15)
    at prepare (/home/ray/.npm-global/lib/node_modules/vuepress/lib/prepare.js:37:25)
    at dev (/home/ray/.npm-global/lib/node_modules/vuepress/lib/dev.js:21:25)
    at args (/home/ray/.npm-global/lib/node_modules/vuepress/bin/vuepress.js:104:12)
    at Command.program.command.description.option.option.action (/home/ray/.npm-global/lib/node_modules/vuepress/bin/vuepress.js:31:21)
    at Command.listener (/home/ray/.npm-global/lib/node_modules/vuepress/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/home/ray/.npm-global/lib/node_modules/vuepress/node_modules/commander/index.js:651:12)
    at Command.parse (/home/ray/.npm-global/lib/node_modules/vuepress/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/ray/.npm-global/lib/node_modules/vuepress/bin/vuepress.js:96:9)
```

**Comment by cfjedimaster** [comment]
Sorry, my vuepress CLI was out of date.
